@startuml
title GameManager.gameLoop()の詳細
start
:static変数の初期化;
:各種画面の作成;
:キャラクターの生成;
:各種イベントハンドラの登録;
:その他の初期化;
:音を再生;

repeat
    note right
    普通のループになっていますが、
    AnimationTimerでループしています
    end note

    :もし、GameViewPaneがフォーカスされていないのなら、
    フォーカスする;
    :プレイヤーを動かす;
    note right
    もし、キーが押されたなら、(WASD)その方向に
    動かす。
    同時にキーが押されても、先に押された
    方向にしか動かない。
    +スクロールする
    end note
    :500/1の確率で敵が発生;
    :スペースキーが押されたなら、対象のhandle()を呼ぶ;
    :各種キーが押されたなら、他の画面を表示;
    :キャラクターのupdate();
    :敵を処理する;
    :当たり判定を処理;
    :変なところに画面がいかないように、
    補正する;
    :カメラを動かす;
    :ステータスメッセージが常に同じ位置に見えるようにする;
    :天かすやHPの表示を更新;
repeat while (エラー発生)
stop
@enduml
